name: Python CI pārbaude

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14.3'

      - name: Installet pytest
        run: |
          pip install pytest
      - name: Palaist testus
        run: python -m pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Buvet image
        run: docker build -t app:v.1.0.${{ github.run_number }} .
