name: Python CI pārbaude

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14.3'

      - name: Installet pytest
        run: |
          pip install pytest
      - name: Palaist testus
        run: python -m pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Ieiet reģistra
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Buvet image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_ID=ghcr.io/$REPO_NAME/app
        
          docker build -t $IMAGE_ID:v.1.1.${{ github.run_number }} .
          docker push $IMAGE_ID:v.1.1.${{ github.run_number }}